name: peak_analysis
dependencies:
  - python
  - pandas
  - numpy
  - traitlets==4.3.3  # needed for vscode compatibility
  - ipykernel
  - scipy
  - matplotlib
  - seaborn
  - openpyxl
  - pybaselines
  - statsmodels
  - flake8
  - black
  - pip 
  - polars